version: "3.1"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-bjvalmaseda-blog
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - bjvalmaseda-blog

  mysql:
    image: mysql:8.0
    container_name: mysql-bjvalmaseda-blog
    restart: unless-stopped
    ports:
      - 33006:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "blog"
      MYSQL_USER: "blog"
      MYSQL_PASSWORD: "blog"
      MYSQL_ROOT_PASSWORD: "root.pass"
      MYSQL_ROOT_HOST: "%"
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      - bjvalmaseda-blog

  php:
    image: ghcr.io/bjvalmaseda92/laravel-devenv:v1.0 #my own image from Github Container
    container_name: php-bjvalmaseda-blog
    restart: unless-stopped #
    volumes: # carpeta de proyecto local
      - ./:/var/www/html
    networks:
      - test-auth # red
    expose:
      - 9000
networks:
  bjvalmaseda-blog:

volumes:
  dbdata:
